### PR TITLE
Update dependencies

### LINKED ISSUE #13: Failed to install `typed-ast`
I encountered following error when running `poetry install`, it failed at installing `typed-ast`. Looks like we need to upgrade `mypy`? `mypy` 1.0.1 works fine.

```
$ poetry install                                                                                                                                                                                                      [14:04:08]
Installing dependencies from lock file

Package operations: 1 install, 22 updates, 0 removals

  • Updating pycparser (2.21 -> 2.20)
  • Updating attrs (22.2.0 -> 21.2.0)
  • Updating cffi (1.15.1 -> 1.14.5)
  • Updating iniconfig (2.0.0 -> 1.1.1)
  • Updating lazy-object-proxy (1.9.0 -> 1.6.0)
  • Updating packaging (23.0 -> 20.9)
  • Updating pluggy (1.0.0 -> 0.13.1)
  • Updating wrapt (1.15.0 -> 1.12.1)
  • Updating astroid (2.14.2 -> 2.5.6)
  • Updating click (8.1.3 -> 8.0.1)
  • Updating coverage (7.2.1 -> 5.5): Installing...
  • Updating isort (5.11.5 -> 5.8.0)
  • Updating mccabe (0.7.0 -> 0.6.1)
  • Updating mypy-extensions (1.0.0 -> 0.4.3)
  • Updating pathspec (0.11.0 -> 0.8.1)
  • Updating pytest (7.2.1 -> 6.2.4)
  • Installing typed-ast (1.4.3): Failed

  CalledProcessError

  Command '['/Users/guojiubo/Outlook/protool/venv/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--isolated', '--no-input', '--prefix', '/Users/guojiubo/Outlook/protool/venv', '--no-deps', '/Users/guojiubo/Library/Caches/pypoetry/artifacts/e8/b0/5f/4ab9773b62c82da44aa681d6aed60b263501dfb4d522dbeaa804479bf2/typed_ast-1.4.3.tar.gz']' returned non-zero exit status 1.

  at /opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py:528 in run
       524│             # We don't call process.wait() as .__exit__ does that for us.
       525│             raise
       526│         retcode = process.poll()
       527│         if check and retcode:
    →  528│             raise CalledProcessError(retcode, process.args,
       529│                                      output=stdout, stderr=stderr)
       530│     return CompletedProcess(process.args, retcode, stdout, stderr)
       531│ 
       532│ 

The following error occurred when trying to handle this error:


  EnvCommandError

  Command ['/Users/guojiubo/Outlook/protool/venv/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--isolated', '--no-input', '--prefix', '/Users/guojiubo/Outlook/protool/venv', '--no-deps', '/Users/guojiubo/Library/Caches/pypoetry/artifacts/e8/b0/5f/4ab9773b62c82da44aa681d6aed60b263501dfb4d522dbeaa804479bf2/typed_ast-1.4.3.tar.gz'] errored with the following return code 1, and output: 
  Processing /Users/guojiubo/Library/Caches/pypoetry/artifacts/e8/b0/5f/4ab9773b62c82da44aa681d6aed60b263501dfb4d522dbeaa804479bf2/typed_ast-1.4.3.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'done'
  Building wheels for collected packages: typed-ast
  • Updating isort (5.11.5 -> 5.8.0)
  • Updating mccabe (0.7.0 -> 0.6.1)
  • Updating mypy-extensions (1.0.0 -> 0.4.3)
  • Updating pathspec (0.11.0 -> 0.8.1)
  • Updating pytest (7.2.1 -> 6.2.4)
  • Installing typed-ast (1.4.3): Failed

  CalledProcessError

  Command '['/Users/guojiubo/Outlook/protool/venv/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--isolated', '--no-input', '--prefix', '/Users/guojiubo/Outlook/protool/venv', '--no-deps', '/Users/guojiubo/Library/Caches/pypoetry/artifacts/e8/b0/5f/4ab9773b62c82da44aa681d6aed60b263501dfb4d522dbeaa804479bf2/typed_ast-1.4.3.tar.gz']' returned non-zero exit status 1.

  at /opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py:528 in run
       524│             # We don't call process.wait() as .__exit__ does that for us.
       525│             raise
       526│         retcode = process.poll()
       527│         if check and retcode:
    →  528│             raise CalledProcessError(retcode, process.args,
       529│                                      output=stdout, stderr=stderr)
       530│     return CompletedProcess(process.args, retcode, stdout, stderr)
       531│ 
       532│ 

The following error occurred when trying to handle this error:


  EnvCommandError

  Command ['/Users/guojiubo/Outlook/protool/venv/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--isolated', '--no-input', '--prefix', '/Users/guojiubo/Outlook/protool/venv', '--no-deps', '/Users/guojiubo/Library/Caches/pypoetry/artifacts/e8/b0/5f/4ab9773b62c82da44aa681d6aed60b263501dfb4d522dbeaa804479bf2/typed_ast-1.4.3.tar.gz'] errored with the following return code 1, and output: 
  Processing /Users/guojiubo/Library/Caches/pypoetry/artifacts/e8/b0/5f/4ab9773b62c82da44aa681d6aed60b263501dfb4d522dbeaa804479bf2/typed_ast-1.4.3.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'done'
  Building wheels for collected packages: typed-ast
  • Updating coverage (7.2.1 -> 5.5)
  • Updating isort (5.11.5 -> 5.8.0)
  • Updating mccabe (0.7.0 -> 0.6.1)
  • Updating mypy-extensions (1.0.0 -> 0.4.3)
  • Updating pathspec (0.11.0 -> 0.8.1)
  • Updating pytest (7.2.1 -> 6.2.4)
  • Installing typed-ast (1.4.3): Failed

  CalledProcessError

  Command '['/Users/guojiubo/Outlook/protool/venv/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--isolated', '--no-input', '--prefix', '/Users/guojiubo/Outlook/protool/venv', '--no-deps', '/Users/guojiubo/Library/Caches/pypoetry/artifacts/e8/b0/5f/4ab9773b62c82da44aa681d6aed60b263501dfb4d522dbeaa804479bf2/typed_ast-1.4.3.tar.gz']' returned non-zero exit status 1.

  at /opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py:528 in run
       524│             # We don't call process.wait() as .__exit__ does that for us.
       525│             raise
       526│         retcode = process.poll()
       527│         if check and retcode:
    →  528│             raise CalledProcessError(retcode, process.args,
       529│                                      output=stdout, stderr=stderr)
       530│     return CompletedProcess(process.args, retcode, stdout, stderr)
       531│ 
       532│ 

The following error occurred when trying to handle this error:


  EnvCommandError

  Command ['/Users/guojiubo/Outlook/protool/venv/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--isolated', '--no-input', '--prefix', '/Users/guojiubo/Outlook/protool/venv', '--no-deps', '/Users/guojiubo/Library/Caches/pypoetry/artifacts/e8/b0/5f/4ab9773b62c82da44aa681d6aed60b263501dfb4d522dbeaa804479bf2/typed_ast-1.4.3.tar.gz'] errored with the following return code 1, and output: 
  Processing /Users/guojiubo/Library/Caches/pypoetry/artifacts/e8/b0/5f/4ab9773b62c82da44aa681d6aed60b263501dfb4d522dbeaa804479bf2/typed_ast-1.4.3.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'done'
  Building wheels for collected packages: typed-ast
    Building wheel for typed-ast (pyproject.toml): started
    Building wheel for typed-ast (pyproject.toml): finished with status 'error'
    error: subprocess-exited-with-error
    
    × Building wheel for typed-ast (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> [26 lines of output]
        running bdist_wheel
        running build
        running build_py
        creating build
        creating build/lib.macosx-13-arm64-cpython-311
        creating build/lib.macosx-13-arm64-cpython-311/typed_ast
        copying typed_ast/conversions.py -> build/lib.macosx-13-arm64-cpython-311/typed_ast
        copying typed_ast/__init__.py -> build/lib.macosx-13-arm64-cpython-311/typed_ast
        copying typed_ast/ast3.py -> build/lib.macosx-13-arm64-cpython-311/typed_ast
        copying typed_ast/ast27.py -> build/lib.macosx-13-arm64-cpython-311/typed_ast
        creating build/lib.macosx-13-arm64-cpython-311/typed_ast/tests
        copying ast3/tests/test_basics.py -> build/lib.macosx-13-arm64-cpython-311/typed_ast/tests
        running build_ext
        building '_ast27' extension
        creating build/temp.macosx-13-arm64-cpython-311
        creating build/temp.macosx-13-arm64-cpython-311/ast27
        creating build/temp.macosx-13-arm64-cpython-311/ast27/Custom
        creating build/temp.macosx-13-arm64-cpython-311/ast27/Parser
        creating build/temp.macosx-13-arm64-cpython-311/ast27/Python
        clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -Iast27/Include -I/Users/guojiubo/Outlook/protool/venv/include -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c ast27/Custom/typed_ast.c -o build/temp.macosx-13-arm64-cpython-311/ast27/Custom/typed_ast.o
        In file included from ast27/Custom/typed_ast.c:3:
        ast27/Custom/../Include/compile.h:5:10: fatal error: 'code.h' file not found
        #include "code.h"
                 ^~~~~~~~
        1 error generated.
        error: command '/usr/bin/clang' failed with exit code 1
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for typed-ast
  Failed to build typed-ast
  ERROR: Could not build wheels for typed-ast, which is required to install pyproject.toml-based projects
  

  at ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/poetry/utils/env.py:1540 in _run
      1536│                 output = subprocess.check_output(
      1537│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1538│                 )
      1539│         except CalledProcessError as e:
    → 1540│             raise EnvCommandError(e, input=input_)
      1541│ 
      1542│         return decode(output)
      1543│ 
      1544│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:


  PoetryException

  Failed to install /Users/guojiubo/Library/Caches/pypoetry/artifacts/e8/b0/5f/4ab9773b62c82da44aa681d6aed60b263501dfb4d522dbeaa804479bf2/typed_ast-1.4.3.tar.gz

  at ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/poetry/utils/pip.py:58 in pip_install
       54│ 
       55│     try:
       56│         return environment.run_pip(*args)
       57│     except EnvCommandError as e:
    →  58│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       59│ 

  • Updating typing-extensions (4.5.0 -> 3.10.0.0)
(venv) FAIL
```

### LINKED ISSUE #14: AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
It seems `pyOpenSSL` needs to be upgrade to >=21.0.0 (to work with `cryptography` 39.0.1) to fix following issue:

```
Exception has occurred: AttributeError
module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
  File "/Users/guojiubo/Outlook/protool/protool/__init__.py", line 16, in <module>
    import OpenSSL
  File "/Users/guojiubo/Outlook/protool/tests/test_parsing.py", line 9, in <module>
    import protool
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```

Associated changes: https://github.com/pyca/pyopenssl/pull/982

### PR DESCRIPTION
**Pull request by guojiubo**
- Update `pyOpenSSL` to fix runtime issue: #14 
- Update `mypy` to fix dev-dependencies installation issue: #13

### CODE REVIEW

**Review by luras-oil — APPROVED** [review]

File: pyproject.toml [hunk 1]
```diff
@@ -31,12 +31,12 @@ classifiers = [
 protool = 'protool:command_line.run'
 
 [tool.poetry.dependencies]
-python = "^3.6.2"
-pyOpenSSL ="^19.0.0"
+python = "^3.7"
```
Comment (ghost) [inline pyproject.toml]: I ran into this by chance yesterday. You may need to set this to `^3.7.2` to ensure Pylint works when it gets updated. (Might be worth doing all dev dependencies in on go)

Comment (guojiubo) [reply pyproject.toml]: Updated all the dev-dependencies and fixed linting issues, please take another look, thanks.

**Review by dalemyers — APPROVED** [review]
