### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

### ISSUE THREAD

**Issue by guojiubo** [microsoft/protool#14]
It seems `pyOpenSSL` needs to be upgrade to >=21.0.0 (to work with `cryptography` 39.0.1) to fix following issue:

```
Exception has occurred: AttributeError
module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
  File "/Users/guojiubo/Outlook/protool/protool/__init__.py", line 16, in <module>
    import OpenSSL
  File "/Users/guojiubo/Outlook/protool/tests/test_parsing.py", line 9, in <module>
    import protool
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```

Associated changes: https://github.com/pyca/pyopenssl/pull/982
